In [7]:
import numpy as np

In [16]:
numpy_array = np.array([1,2,3,4], dtype = float)
print(numpy_array)
type(numpy_array)
numpy_array.shape

[1. 2. 3. 4.]


(4,)

In [17]:
#nD Array
numpy_array_n = np.array([(1,2,3,4), (1,2,3,4)])
print(numpy_array_n)

[[1 2 3 4]
 [1 2 3 4]]


In [18]:
numpy_array_n.shape

(2, 4)

In [24]:
# create a numpy array of zero
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
# create a numpy array of One
y = np.ones((3,2))
y

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
# create a numpy array of a particular value
z = np.full((3,4), 5)
z

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [27]:
# create an identity matrix
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
# create a numpy array of a random value
b = np.random.random((3,4))
b

array([[0.99564149, 0.58430033, 0.43718192, 0.34325642],
       [0.36873507, 0.23372517, 0.50901124, 0.68033596],
       [0.15726171, 0.09005551, 0.9382509 , 0.66491772]])

In [32]:
# create a numpy array of a random integer value with speacifc range
b = np.random.randint(10,100,(3,4))
b

array([[20, 63, 52, 66],
       [22, 30, 85, 99],
       [69, 84, 81, 94]])

In [34]:
# array of evenly value 
d = np.linspace(10,40,5)
d


array([10. , 17.5, 25. , 32.5, 40. ])

In [36]:
# array of evenly value  specific step
d = np.arange(10,30,2)
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [39]:
# convert a list to numpy array 
list = [1,2,3,4]

np_array = np.asanyarray(list)
type(np_array)


numpy.ndarray

Analysing a numpy array

In [41]:
array = np.random.randint(10,40,(3,5))


In [44]:
# array dimensions 
array.shape

(3, 5)

In [45]:
# number of dimensions
array.ndim


2

In [46]:
#number of  element of array
array.size

15

In [47]:
# checking data of a value of a array
array.dtype

dtype('int64')